onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - unrs-resolver

approvedBuilds:
  - core-js@3.50.0
  - esbuild@0.18.20
  - esbuild@0.25.12

allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
